# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticker < Formula
  desc "Terminal stock ticker with live updates and position tracking"
  homepage "https://github.com/hwyll/ticker"
  version "0.0.1"
  license "GPLv3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-amd64.tar.gz"
    sha256 "c39ea9d7ecc3909bca087140202923342ba2dfa9e1c89f3ea64f9e89b12100d2"

    def install
      bin.install "ticker"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-arm64.tar.gz"
    sha256 "ab0eab25b62dba49546dafa4d7442e2059c42b4b5758c17b2d550d94c5cfa102"

    def install
      bin.install "ticker"
    end
  end
end
