# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticker < Formula
  desc "Terminal stock ticker with live updates and position tracking"
  homepage "https://github.com/hwyll/ticker"
  version "0.0.1"
  license "GPLv3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-amd64.tar.gz"
    sha256 "8b46f37d754dac86d312acfbe78a61b4545c07a4da3bf6239b2c9b4079696fe0"

    def install
      bin.install "ticker"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-arm64.tar.gz"
    sha256 "6b0d9269c4c8deaba11dedd03f89c8d1761ea41145549de66d03081213002897"

    def install
      bin.install "ticker"
    end
  end
end
