# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticker < Formula
  desc "Terminal stock ticker with live updates and position tracking"
  homepage "https://github.com/hwyll/ticker"
  version "0.0.1"
  license "GPLv3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-amd64.tar.gz"
    sha256 "c2535b89e2fb23d265402486b1c0d82febcb877f3b71c084a0df89b37300d0b2"

    def install
      bin.install "ticker"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-arm64.tar.gz"
    sha256 "33fcef6c6c9b7aa559bdb5170342632deb6d5a32e9fd7b4261fab3750346c018"

    def install
      bin.install "ticker"
    end
  end
end
