# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticker < Formula
  desc "Terminal stock ticker with live updates and position tracking"
  homepage "https://github.com/hwyll/ticker"
  version "0.0.1"
  license "GPLv3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-amd64.tar.gz"
    sha256 "8535e493c6f7d1dc2e93ddd1491b595c651e705b39e5e7db89effb56d5e88822"

    def install
      bin.install "ticker"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hwyll/ticker/releases/download/v0.0.1/ticker-0.0.1-mac-arm64.tar.gz"
    sha256 "406b1ee7d86cb2920eff535a25223ec81f8f119a7e5c50a2cea9aa7fc00c5bd2"

    def install
      bin.install "ticker"
    end
  end
end
