# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typtea < Formula
  desc "Terminal based typing test"
  homepage "https://github.com/hwyll/typtea"
  version "0.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hwyll/typtea/releases/download/v0.0.2/typtea-0.0.2-mac-amd64.tar.gz"
    sha256 "6882d911d186eb03ef4c864b3e21a4c57b3a7d68d24fb6c093978d999c57aec4"

    def install
      bin.install "typtea"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hwyll/typtea/releases/download/v0.0.2/typtea-0.0.2-mac-arm64.tar.gz"
    sha256 "cfdda35766686903e9ccc5997badca4ce34e43e60a80626e116dd7619f3bcf62"

    def install
      bin.install "typtea"
    end
  end
end
